name: bridgescaler
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - pyarrow
  - pytest
  - sphinx
  - xarray
  - pip:
    - pytdigest
    - sphinx-book-theme
    - .
