name: bridgescaler
channels:
  - conda-forge
dependencies:
  - python=3.13
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - pyarrow
  - pytest
  - sphinx
  - xarray
  - crick
  - numba
  - sphinx-book-theme
  - pip:
    - .
