name: bridgescaler
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy>=1.23.0
  - scipy>=1.11.0
  - pandas
  - scikit-learn
  - pyarrow
  - pytest
  - sphinx
  - xarray
  - crick
  - pip:
    - sphinx-book-theme
    - pytdigest
